targets:
  $default:
    sources:
      - swagger/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "swagger"
          output_folder: "lib/generated/swagger"